- name: Create VM3 in VM1
  hosts: vm1
  become: true
  vars:
    image_dir: "/var/lib/libvirt/images"
    base_image_name: "ubuntu-base.qcow2"
    base_image_dir: "../img/ubuntu.img"
    cloud_init_dir: "../template/cloud_init.cfg.j2"
    vm3_disk_name: "vm3.qcow2"
    vm3_disk_size: "10G"
    vm3_cloud_init_iso: "vm3_seed.iso"
    vm3_name: "vm3"
  tasks:
    - name: Ensure image directory exists
      file:
        path: "{{ image_dir }}"
        state: directory
        owner: libvirt-qemu
        group: kvm
        mode: "0755"

    - name: Copy base image to libvirt directory
      copy:
        src: "{{ base_image_dir }}"
        dest: "{{ image_dir }}/{{ base_image_name }}"
        owner: libvirt-qemu
        group: kvm
        mode: 0660

    - name: Create VM3 qcow2 overlay disk
      command: >
        qemu-img create
        -f qcow2
        -F qcow2
        -b {{ image_dir }}/{{ base_image_name }}
        {{ image_dir }}/{{ vm3_disk_name }}
        {{ vm3_disk_size }}
      args:
        creates: "{{ image_dir }}/{{ vm3_disk_name }}"

    - name: Render cloud-init user-data for VM3
      template:
        src: "{{ cloud_init_dir }}"
        dest: "/tmp/user-data"
        mode: "0644"

    - name: Render cloud-init meta-data for VM3
      copy:
        dest: "/tmp/meta-data"
        mode: "0644"
        content: |
          instance-id: {{ vm3_name }}
          local-hostname: {{ vm3_name }}

    - name: Create cloud-init ISO for VM3
      command: >
        cloud-localds
        {{ image_dir }}/{{ vm3_cloud_init_iso }}
        /tmp/user-data
        /tmp/meta-data
      args:
        creates: "{{ image_dir }}/{{ vm3_cloud_init_iso }}"

    - name: Set ownership for cloud-init ISO
      file:
        path: "{{ image_dir }}/{{ vm3_cloud_init_iso }}"
        owner: libvirt-qemu
        group: kvm
        mode: "0644"

    - name: Create VM3 instance
      command: >
        virt-install
         --name {{ vm3_name }}
         --memory 2048
         --vcpus 2
         --cpu host
         --disk path={{ image_dir }}/{{ vm3_disk_name }},format=qcow2,bus=virtio
         --disk path={{ image_dir }}/{{ vm3_cloud_init_iso }},device=cdrom
         --os-variant ubuntu24.04
         --import
         --network network=default,model=virtio
         --graphics none
         --console pty,target_type=serial
         --noautoconsole
