- name: Migrate VM3 from VM1 to vm2
  host: VM1
  vars:

  tasks:
  - name: Check default storage pool for vm3
    command: >
      

  - name: Migrate 
    command: >
      sudo virsh migrate vm3 \
      qemu+ssh://ubuntu@192.168.122.121/system \
      --live \
      --copy-storage-all \
      --persistent \
      --undefinesource \
      --verbose
